config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :info_requests
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/info_request.rb
class InfoRequest < ActiveRecord::Base
  
  attr_accessible :creator, :title

  belongs_to :creator, :class_name => "User"
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  has_many :created_info_requests, :foreign_key => "creator_id", :class_name => "InfoRequest"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index

  	if current_user.nil?
  	else
  		if current_user.has_role? :admin
  			@info_requests = InfoRequest.select("info_requests.*, users.name").
   	     		joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id')
   	     	
  		else
  			@info_requests = InfoRequest.select("info_requests.*, users.name").
   	     		joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id').where("creator_id = #{current_user.id}")
  		end

      redirect_to :controller => 'users', :action => 'show', :id => current_user.id
      
  	end

    # if !current_user.nil? && !current_user.has_role? :admin
   	#    @info_requests = InfoRequest.select("info_requests.*, users.*").
   	#      joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id').where("creator_id = #{current_user.id}")
   	# elsif ((!current_user.nil?) && (current_user.has_role? :admin))
   	# 	@info_requests = InfoRequest.all   		
   	# end

  end

end

app/controllers/info_requests_controller.rb
class InfoRequestsController < ApplicationController

  def new
  #	@info_request = InfoRequest.new
  end

  def create
  	current_user.created_info_requests.create(params[:info_request])

    #flash[:notice] = "#{@info_request.title} was successfully created."
    redirect_to user_path @current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'NO TIENE PERMISO PARA VER ESTA PAGINA.'
    @users = User.all
  end

  def show
  @user = User.find(params[:id])

   	if !params[:info_request].nil?
     #@specific_request = InfoRequest.find(params[:info_request])
     @specific_request = InfoRequest.select("info_requests.*, users.name").
   	     		joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id').where("info_requests.id = #{params[:info_request]}").last
    # @specific_request = InfoRequest.select("info_requests.*, users.name").
   	 #    		joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id').where("id = 1")
   	 # @specific_request = InfoRequest.find(:all, :joins => "INNER JOIN users ON users.id = info_requests.creator_id",
   	 # 	:select => "info_requests.title, users.name")
   	 # @specific_request = @specific_request.where(:id => "1")
   	     		

    else
    end
   
    if current_user.nil?
  	else
  		if current_user.has_role? :admin
  			@info_requests = InfoRequest.select("info_requests.*, users.name").
   	     		joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id')
   	     	
  		else
  			@info_requests = InfoRequest.select("info_requests.*, users.name").
   	     		joins('LEFT OUTER JOIN users ON users.id = info_requests.creator_id').where("creator_id = #{current_user.id}")
  		end
  	end
  end

  respond_to do |format|
    format.html { render 'show' }
    format.js
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_requests_helper.rb
module InfoRequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="center hero-unit">

	
		<h1>Bienvenidos al Portal de la Central de Información</h1>
		<br>
		<h2>Aquí encontrarás todo lo relacionado con la información de Méderi</h2>
		<%= link_to "Ingresar",  new_user_session_path, 
                                class: "btn btn-large btn-primary" %>
	
	
</div>

app/views/info_requests/create.html.erb
<h1>InfoRequests#create</h1>
<p>Find me in app/views/info_requests/create.html.erb</p>

app/views/info_requests/new.html.erb
<h1>Creación de solicitud</h1>
<%= form_tag info_requests_path, :method=>'post' do %>

  <%= label :info_request, :title, 'Título' %>
  <%= text_field :info_request, 'title' %>

  <%= label :info_request, :owner_id, 'Dueño de la solicitud' %>
  <%= collection_select(:info_request, :owner_id, User.all, :id, :name) %>

  <%= submit_tag 'Guardar solicitud' %>
<%end%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Central de Información", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Cerrar sesión', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Ingresar', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Editar cuenta', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Administración', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Solicitar clave', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails3 Bootstrap Devise Cancan" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "jquery", "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_info_request_detail.html.erb
<% if !@specific_request.nil? %>
 <h2> Detalle de la solicitud </h2>
  <table class = "table" id ="ird_table">
  	<tr>
    	<th>Titulo</th>
    	<th>Creador</th>
      <th>Creada en</th>
  	</tr>

   
  	<tr>
    	<td><%= @specific_request.title %></td>  
    	<td><%= @specific_request.name%></td>
      <td><%= @specific_request.created_at %></td>
  	</tr>
<% else
   end %>
</table>

app/views/shared/_info_request_table.html.erb
<table class = "table">
  	<tr>
    	<th>Titulo</th>
    	<th>Creador</th>
  	</tr>

   	<% @info_requests.each do |ir| %>
  	<tr>
    	<td><%= link_to ir.title, { :info_request => ir.id, :controller => "users", :action => "show"}, {:remote => true, :id => "new_review"} %></td>  
    	<td><%= ir.name %></td>
  	</tr>
  	<% end %>
</table>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="center hero-unit">

	<% if user_signed_in? %>
		
	    <h1>Bienvenido <%=@user.name %>!</h1>
		<br>
		<h2>Existen <%= @info_requests.count %> solicitudes de información</h2>
		<br>
		<%= link_to "Crear nueva solicitud",  new_info_request_path, 
                                class: "btn btn-large btn-primary" %>

		<div><%= render partial: 'shared/info_request_table' %></div>

		<div id = "ird_table"><%= render partial: 'shared/info_request_detail' %></div>
       
		

	<% else %>
		<%= redirect_to root_path %>
	<% end %>
	
</div>

app/views/users/show.js.erb
$("#ird_table").empty()
$("#ird_table").append("<%= escape_javascript(render(:partial => 'shared/info_request_detail')) %>");